id: P000649
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-16 15:56:46.635483
source_metadata:
  id: bdr:W1KG24759
  title: བོད་ལུགས་གསོ་རིག་གི་དངུལ་ཁབ་ལག་ལེན།
  author: ''
  volumes:
    32a78ba9afca4cf4a817b52030f8ae0b:
      image_group_id: I1KG24761
      title: ''
      volume_number: 1
      total_pages: 233
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
