id: I49F1F991
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T16:29:42+00:00'
last_modified: '2022-06-07T12:33:18.856686+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG24759
  title: བོད་ལུགས་གསོ་རིག་གི་དངུལ་ཁབ་ལག་ལེན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    4F85:
      image_group_id: I1KG24761
      title: ''
      total_pages: 233
      order: 1
      base_file: 4F85.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
